---
title: "NY Times US States COVID-19 Analysis"
author: "David J Jackson"
date: "June 12, 2020 16:25 UD/UT"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=9, fig.height=6)
library(tidyverse)
library(RSQLite)
library(plotly)
library(readODS)
```

## NY Times US States Data Analysis
* GitHub: https://github.com/nytimes/covid-19-data.git


```{r, echo=FALSE}
rm(list=ls())
us_states <- data.table::fread("../COVID-19-NYTimes-data//us-states.csv")

us_total <- us_states %>% group_by(date) %>% 
summarise(Cases=sum(cases), Deaths = sum(deaths),                                                                   DeathRate = Deaths/Cases)

us_state_total <- us_states %>% group_by(state,date) %>% 
  summarise(Cases=sum(cases),                                                             Deaths = sum(deaths),  DeathRate = Deaths/Cases)

```
```{r,echo=FALSE}
us_counties <- data.table::fread("../COVID-19-NYTimes-data/us-counties.csv")
us_county_summary <- us_counties %>% group_by(state,county,date) %>% summarise(Cases=sum(cases),Deaths = sum(deaths),DeathRate = Deaths/Cases)
```
```{r}
db <- dbConnect(SQLite(), dbname="../COVIDDB/CORVID.sqlite3")
shutdown <- dbGetQuery(db, "SELECT * from shutdown;")

```



```{r}
sd <- shutdown %>% ggplot() + geom_col(aes(x=Delay,y=reorder(State,Delay))) +
  labs(title="Elasped Days from First Confirmed Case(WA)",
       x="Delayed in Days",y="US States(and DC",
       caption ="(Shutdown Dates = https://www.nbcnews.com)")
ggplotly(sd)
```

```{r,echo=FALSE}
db <- dbConnect(SQLite(), dbname="../COVIDDB/CORVID.sqlite3")
us_states$date <- as.character(us_states$date)
dbWriteTable(db, "us_states",us_states ,overwrite=TRUE)

us_counties$date <- as.character(us_counties$date)
dbWriteTable(db, "us_counties",us_counties ,overwrite=TRUE)

# dbDisconnect(db)

```


```{r,echo=FALSE}
STATESDAILY <-  us_states %>% 
  group_by(date, state) %>%
  summarise(
    TotalCases = sum(cases, na.rm=TRUE),
    TotalDeaths = sum(deaths, na.rm=TRUE)
  ) %>%
  group_by(state) %>%
  arrange(desc(date)) %>%
  mutate(
    PreviousTotalCases = lead(TotalCases),
    PreviousTotalDeaths = lead(TotalDeaths)
  ) %>%
  ungroup() %>%
  na.omit()
STATESDAILY <- STATESDAILY %>% mutate(new_cases = TotalCases - PreviousTotalCases)
STATESDAILY <- STATESDAILY %>% mutate(new_deaths = TotalDeaths - PreviousTotalDeaths)
STATESDAILY <- STATESDAILY %>% mutate(death_rate = new_deaths / new_cases)
STATESDAILY$date <- as.character(STATESDAILY$date)
dbWriteTable(db, "STATESDAILY",STATESDAILY ,overwrite=TRUE)
```


```{r,echo=FALSE}
COUNTYDAILY <-  us_counties %>% 
  group_by(date,state, county) %>%
  summarise(
    TotalCases = sum(cases, na.rm=TRUE),
    TotalDeaths = sum(deaths, na.rm=TRUE)
  ) %>%
  group_by(state,county) %>%
  arrange(desc(date)) %>%
  mutate(
    PreviousTotalCases = lead(TotalCases),
    PreviousTotalDeaths = lead(TotalDeaths)
  ) %>%
  ungroup() %>%
  na.omit()
COUNTYDAILY <- COUNTYDAILY%>% mutate(new_cases = TotalCases - PreviousTotalCases)
COUNTYDAILY <- COUNTYDAILY%>% mutate(new_deaths = TotalDeaths - PreviousTotalDeaths)
COUNTYDAILY <- COUNTYDAILY%>% mutate(death_rate = new_deaths/new_cases)
COUNTYDAILY$date <- as.character(COUNTYDAILY$date)
dbWriteTable(db, "COUNTYDAILY",COUNTYDAILY,overwrite=TRUE)
```

#### Summary of Cases,Deaths  and Death Rate by Date

```{r,echo=FALSE}
us_total %>% plot_ly() %>% add_lines(x=~date,y=~Cases) %>%
  layout(title="US Daily Summary of Cases")

us_total %>% plot_ly() %>% add_lines(x=~date,y=~Deaths) %>%
  layout(title="US Daily Summary of Deaths")

us_total %>% plot_ly() %>% add_lines(x=~date,y=~DeathRate) %>%
  layout(title="US Daily Rate of Death")
```

#### Summary of Cases and Deaths by State

```{r,echo=FALSE}
 sc <- ggplot(us_state_total) + geom_col(aes(x=date,y=Cases,fill=state)) +
  labs(title="Daily Cases Summary by Date") 
ggplotly(sc)

sd <- ggplot(us_state_total) + geom_col(aes(x=date,y=Deaths,fill=state)) +
  labs(title="Daily Deaths Summary by State") 
ggplotly(sd)

```

#### Summary of Ohio Deaths and Cases

```{r,echo=FALSE}

ohio_counties <- us_county_summary %>% filter(state=="Ohio")
oh1 <- ggplot(ohio_counties) + geom_col(aes(x=date,y=Cases)) +
  labs(title="Ohio Daily Cases Summary by Date")
ggplotly(oh1)

oh2 <- ggplot(ohio_counties) + geom_col(aes(x=date,y=Deaths)) +
  labs(title="Ohio Daily Deaths Summary by Date")
ggplotly(oh2)
```
```{r,echo=FALSE}
oh3 <- ggplot(ohio_counties) + geom_col(aes(x=date,y=Cases,fill=county)) +
  labs(title="Ohio/county Daily Cases Summary by Date")
ggplotly(oh3)

oh4 <- ggplot(ohio_counties) + geom_col(aes(x=date,y=Deaths,fill=county)) +
  labs(title="Ohio/County Daily Deaths Summary by Date")
ggplotly(oh4)
```
```{r}
statesSum <-us_states %>% group_by(state) %>% 
  summarise(
    tc = sum(cases),
    td = sum(deaths)) 

ggplot(statesSum) + geom_point(aes(x=tc,y=state,size=tc,col=tc)) +
   scale_x_continuous(labels = scales::comma) +
  labs(title="Total Cases by States",subtitle="(As of May 18, 2020)",
       x="Total Cases",y="US States")


ggplot(statesSum) + geom_point(aes(x=tc,y=state,size=td,col=td)) +
  scale_x_continuous(labels = scales::comma) +
  labs(title="Total Deaths by States",subtitle="(As of May 18, 2020)",x="Total Deaths",y="US States")
  
```



```{r}
dbDisconnect(db)
```

